steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME-$BUILD_ID",
        ".",
      ]
images:
  - "$LOCATION-docker.pkg.dev/$PROJECT_ID/$REPO_NAME/$BRANCH_NAME-$BUILD_ID"
